-- Staging: Tally on-chain governance proposals
-- Reads raw JSON and renames columns to snake_case

select
    id as proposal_id,
    onchain_id,
    title,
    description as body,
    status,
    eta,
    discourse_url,
    snapshot_url,
    proposer as proposer_address,
    proposer_name,
    proposer_ens,
    governor_id,
    governor_name,
    organization_id,
    organization_name,
    start_block,
    start_timestamp,
    end_block,
    end_timestamp,
    block_number as created_block,
    block_timestamp as created_timestamp,
    for_votes as for_votes_wei,
    against_votes as against_votes_wei,
    abstain_votes as abstain_votes_wei,
    for_voters,
    against_voters,
    abstain_voters,
    for_percent,
    against_percent,
    abstain_percent,
    quorum
from {{ source('bronze_governance', 'tally_proposals') }}
